version: '3.8'
services:
  shadowsocks:
    build: .
    container_name: shadowsocks
    ports:
      - "8388:8388/tcp"
      # - "8388:8388/udp" #Only tcp is needed with v2ray-plugin
    env_file:
      - ../digitalocean/.env
    volumes:
      - ./dnscrypt-proxy.toml:/etc/dnscrypt-proxy.toml
