version: '3.8'
services:
  mtproxy:
    build: .
    container_name: mtproxy
    ports:
      - "8388:8388/tcp"
      - "8388:8388/udp"
    environment:
      SHADOWSOCKS_METHOD: 
      SHADOWSOCKS_PASSWORD: 
    restart: unless-stopped
    # Uncomment below to mount config for local testing
    # volumes:
    #   - ./dnscrypt-proxy.toml:/etc/dnscrypt-proxy.toml:ro
